---
'headless': False  # type True or False
'interval_time': 10  # seconds (optional)
'disable_before_months': 12  # months (optional)
'disable_on_postnum': 100 # number of maximum posts to get (optional)
'2': 
  link: Google Classroom Link No. 1  # Classroom Name
  login: 12345@gmail.com
  sendfrom: 23456@naver.com
  sendto:
    - abcd@gmail.com
    - efgh@gmail.com
    - ijkl@gmail.com
'2': 
  link: Google Classroom Link No. 2  # Classroom Name
  login: 12345@gmail.com
  sendfrom: 23456@naver.com
  sendto:
    - abcd@gmail.com
    - efgh@gmail.com
    - ijkl@gmail.com
'3': 
  link: Google Classroom Link No. 3  # Classroom Name
  login: 12345@gmail.com
  sendfrom: 23456@naver.com
  sendto:
    - abcd@gmail.com
    - efgh@gmail.com
    - ijkl@gmail.com
'4': 
  link: Google Classroom Link No. 4  # Classroom Name
  login: 12345@gmail.com
  sendfrom: 23456@naver.com
  sendto:
    - abcd@gmail.com
    - efgh@gmail.com
    - ijkl@gmail.com
'5': 
  link: Google Classroom Link No. 5  # Classroom Name
  login: 12345@gmail.com
  sendfrom: 23456@naver.com
  sendto:
    - abcd@gmail.com
    - efgh@gmail.com
    - ijkl@gmail.com