start python3 "C:\Users\leesj\Documents\VS Code\classroom-notifier\src\main.py 1"
start python3 "C:\Users\leesj\Documents\VS Code\classroom-notifier\src\main.py 2"
start python3 "C:\Users\leesj\Documents\VS Code\classroom-notifier\src\main.py 3"
start python3 "C:\Users\leesj\Documents\VS Code\classroom-notifier\src\main.py 4"
start python3 "C:\Users\leesj\Documents\VS Code\classroom-notifier\src\main.py 5"